spring:
  application:
    name: transactional-outbox-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/outboxdb
    username: postgres
    password: ${OUTBOX_DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate # Recommended over 'none' to ensure Flyway and Java match
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

